databases:
  - name: postgres
    databaseName: facenovel_production
    user: facenovel

services:
  - type: web
    name: facenovel
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false